# Generated by Django 4.2.29 on 2026-03-18 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='deadline',
            new_name='due_date',
        ),
    ]
