# Generated by Django 4.2.29 on 2026-03-18 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_rename_deadline_assignment_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='due_date',
            new_name='deadline',
        ),
    ]
